### ISSUE TITLE
what's your GPU memory?

### ISSUE THREAD

**Issue by arieling** [yunjey/show-attend-and-tell#22]
It seems that you tried to load all training data into a numpy array, which causes memory error in my case.  (it works on my 3* titanX 12G GPU)

what's your GPU memory?

**Comment by DongNaeSwellfish** [comment]
It has nothing to do with GPU memory. It happens because the code tries to save all the feature in one pkl file, which matters in RAM. I changed the code, in prepro.py.
I made batchsize to 100 and saved pkl file in every iteration.
Otherwise, you can allocate more swap memory, and you can google the way how to allocate more swap memory.

**Comment by arieling** [comment]
I  mean, when I run train.py the program tried to load all processed images feature from a hickle file. This will be stored in GPU memory I guess...

**Comment by yunjey** [comment]
As @DongNaeSwellfish mentioned, numpy array is related to cpu not gpu. You need more than 40GB RAM to run this project. 
You can control the gpu memory usage by reducing or increasing the batch size during training.

**Comment by thepurpleowl** [comment]
@DongNaeSwellfish @yunjey Can you tell me how to do that?? And by changing prepro.py we also have to change train.py, right??
